name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Create 404.html for SPA routing
      run: |
        cat > dist/404.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>Industrial Partners - Brisbane Warehouse Solutions</title>
            <meta name="description" content="Professional industrial real estate services in Brisbane. Selling and leasing warehouses and industrial properties." />
            <meta name="author" content="Industrial Partners" />
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">

            <!-- Favicon -->
            <link rel="icon" type="image/png" href="/industrial-partners-brisbane/IPlogofavicon (1).png" />

            <meta property="og:title" content="4a08b092-e433-48c7-adac-7f88f8e1d9c5" />
            <meta property="og:description" content="Lovable Generated Project" />
            <meta property="og:type" content="website" />
            <meta property="og:image" content="https://lovable.dev/opengraph-image-p98pqg.png" />

            <script>
              // GitHub Pages SPA 404 redirect handling
              sessionStorage.redirect = location.href;
            </script>
            
            <meta http-equiv="refresh" content="0;URL='/industrial-partners-brisbane/'" />
          </head>
          <body>
            <div id="root"></div>
          </body>
        </html>
        EOF
        
    - name: Fix favicon path for GitHub Pages
      run: |
        sed -i 's|href="/IPlogofavicon|href="/industrial-partners-brisbane/IPlogofavicon|g' dist/index.html
      
    - name: Fix asset paths for GitHub Pages
      run: |
        find dist -type f -name "*.html" -exec sed -i 's|src="/|src="/industrial-partners-brisbane/|g' {} +
        find dist -type f -name "*.html" -exec sed -i 's|href="/|href="/industrial-partners-brisbane/|g' {} +
        find dist -type f -name "*.css" -exec sed -i 's|url(/|url(/industrial-partners-brisbane/|g' {} +
        find dist -type f -name "*.js" -exec sed -i 's|"/"|\"/industrial-partners-brisbane/\"|g' {} +
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist 